name: CI/CD Pipeline for Sample1

on:
  pull_request:
    branches:
      - main  # Runs when code is pushed to 'stage' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

  docker:
    needs: build  # Runs only if 'build' job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t sample1-app .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 sample1-app

  notify:
    needs: docker  # Runs only if 'docker' job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: "psibi0604@gmail.com"  # Replace with your Gmail address
          password: "Sibi*2004"     # Replace with your Gmail app password or normal password (if no 2FA)
          subject: "Deployment Successful"
          body: "The Docker container is running successfully!"
          to: "psibi2004@gmail.com"
          from: "GitHub Actions Bot"

  deploy:
    needs: notify  # Runs only if email is sent successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge stage → main
        run: |
          git config --global user.name "Sibi04"
          git config --global user.email "psibi2004@gmail.com"
          git checkout main
          git merge stage --no-ff
          git push origin main
